DROP INDEX IF EXISTS idx_transactions_date;
DROP INDEX IF EXISTS idx_transactions_account_id;
DROP INDEX IF EXISTS idx_accounts_user_id;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS transaction_type;
DROP TYPE IF EXISTS account_type;
DROP EXTENSION IF EXISTS "uuid-ossp";
