package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"golang.org/x/crypto/bcrypt"

	"hechi-go/graph/generated"
	"hechi-go/graph/model"
	"hechi-go/internal/auth"
	"hechi-go/internal/domain"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password")
	}

	user := &domain.User{
		ID:        uuid.New(),
		Email:     input.Email,
		Name:      input.Name,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	if err := r.UserRepo.Create(ctx, user, string(hash)); err != nil {
		return nil, fmt.Errorf("email already in use")
	}

	token, err := r.Auth.Issue(user.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to issue token")
	}

	return &model.AuthPayload{
		Token: token,
		User:  domainUserToModel(user),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	user, hash, err := r.UserRepo.FindByEmail(ctx, input.Email)
	if err != nil {
		return nil, errors.New("invalid email or password")
	}

	if err := bcrypt.CompareHashAndPassword([]byte(hash), []byte(input.Password)); err != nil {
		return nil, errors.New("invalid email or password")
	}

	token, err := r.Auth.Issue(user.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to issue token")
	}

	return &model.AuthPayload{
		Token: token,
		User:  domainUserToModel(user),
	}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Account, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	initialBalance, err := decimal.NewFromString(input.InitialBalance)
	if err != nil {
		return nil, fmt.Errorf("invalid initial balance: %s", input.InitialBalance)
	}

	account := &domain.Account{
		ID:        uuid.New(),
		UserID:    userID,
		Name:      input.Name,
		Type:      domain.AccountType(input.Type),
		Balance:   initialBalance,
		Currency:  input.Currency,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}

	if err := r.AccountRepo.Create(ctx, account); err != nil {
		return nil, fmt.Errorf("failed to create account")
	}

	return domainAccountToModel(account), nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.Transaction, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	accountID, err := uuid.Parse(input.AccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account id")
	}

	account, err := r.AccountRepo.FindByID(ctx, accountID)
	if err != nil {
		return nil, fmt.Errorf("account not found")
	}
	if account.UserID != userID {
		return nil, errors.New("unauthorized")
	}

	amount, err := decimal.NewFromString(input.Amount)
	if err != nil {
		return nil, fmt.Errorf("invalid amount: %s", input.Amount)
	}

	tx := &domain.Transaction{
		ID:          uuid.New(),
		AccountID:   accountID,
		Amount:      amount,
		Type:        domain.TransactionType(input.Type),
		Category:    input.Category,
		Description: input.Description,
		Date:        input.Date,
		CreatedAt:   time.Now(),
	}

	if err := r.TransactionRepo.Create(ctx, tx); err != nil {
		return nil, fmt.Errorf("failed to create transaction")
	}

	newBalance := account.Balance
	switch tx.Type {
	case domain.TransactionTypeIncome:
		newBalance = newBalance.Add(amount)
	case domain.TransactionTypeExpense:
		newBalance = newBalance.Sub(amount)
	}

	if err := r.AccountRepo.UpdateBalance(ctx, accountID, newBalance); err != nil {
		return nil, fmt.Errorf("failed to update balance")
	}

	return domainTransactionToModel(tx), nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id string) (bool, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return false, errors.New("unauthorized")
	}

	accountID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid account id")
	}

	if err := r.AccountRepo.Delete(ctx, accountID, userID); err != nil {
		return false, fmt.Errorf("failed to delete account")
	}

	return true, nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (bool, error) {
	_, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return false, errors.New("unauthorized")
	}

	txID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid transaction id")
	}

	if err := r.TransactionRepo.Delete(ctx, txID); err != nil {
		return false, fmt.Errorf("failed to delete transaction")
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	user, err := r.UserRepo.FindByID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("user not found")
	}

	accounts, err := r.AccountRepo.FindByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch accounts")
	}

	modelUser := domainUserToModel(user)
	for _, a := range accounts {
		modelUser.Accounts = append(modelUser.Accounts, domainAccountToModel(a))
	}

	return modelUser, nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*model.Account, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	accountID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid account id")
	}

	account, err := r.AccountRepo.FindByID(ctx, accountID)
	if err != nil {
		return nil, fmt.Errorf("account not found")
	}
	if account.UserID != userID {
		return nil, errors.New("unauthorized")
	}

	return domainAccountToModel(account), nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*model.Account, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	accounts, err := r.AccountRepo.FindByUserID(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch accounts")
	}

	var result []*model.Account
	for _, a := range accounts {
		result = append(result, domainAccountToModel(a))
	}
	return result, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, accountID string, limit *int, offset *int) ([]*model.Transaction, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, errors.New("unauthorized")
	}

	accID, err := uuid.Parse(accountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account id")
	}

	account, err := r.AccountRepo.FindByID(ctx, accID)
	if err != nil {
		return nil, fmt.Errorf("account not found")
	}
	if account.UserID != userID {
		return nil, errors.New("unauthorized")
	}

	l, o := 50, 0
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}

	txs, err := r.TransactionRepo.FindByAccountID(ctx, accID, l, o)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, tx := range txs {
		result = append(result, domainTransactionToModel(tx))
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// helpers

func domainUserToModel(u *domain.User) *model.User {
	return &model.User{
		ID:        u.ID.String(),
		Email:     u.Email,
		Name:      u.Name,
		Accounts:  []*model.Account{},
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}
}

func domainAccountToModel(a *domain.Account) *model.Account {
	return &model.Account{
		ID:           a.ID.String(),
		UserID:       a.UserID.String(),
		Name:         a.Name,
		Type:         model.AccountType(a.Type),
		Balance:      a.Balance.String(),
		Currency:     a.Currency,
		Transactions: []*model.Transaction{},
		CreatedAt:    a.CreatedAt,
		UpdatedAt:    a.UpdatedAt,
	}
}

func domainTransactionToModel(tx *domain.Transaction) *model.Transaction {
	return &model.Transaction{
		ID:          tx.ID.String(),
		AccountID:   tx.AccountID.String(),
		Amount:      tx.Amount.String(),
		Type:        model.TransactionType(tx.Type),
		Category:    tx.Category,
		Description: tx.Description,
		Date:        tx.Date,
		CreatedAt:   tx.CreatedAt,
	}
}
