// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Account struct {
	ID           string         `json:"id"`
	UserID       string         `json:"userId"`
	Name         string         `json:"name"`
	Type         AccountType    `json:"type"`
	Balance      string         `json:"balance"`
	Currency     string         `json:"currency"`
	Transactions []*Transaction `json:"transactions"`
	CreatedAt    time.Time      `json:"createdAt"`
	UpdatedAt    time.Time      `json:"updatedAt"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateAccountInput struct {
	Name           string      `json:"name"`
	Type           AccountType `json:"type"`
	Currency       string      `json:"currency"`
	InitialBalance string      `json:"initialBalance"`
}

type CreateTransactionInput struct {
	AccountID   string          `json:"accountId"`
	Amount      string          `json:"amount"`
	Type        TransactionType `json:"type"`
	Category    *string         `json:"category,omitempty"`
	Description *string         `json:"description,omitempty"`
	Date        time.Time       `json:"date"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type Transaction struct {
	ID          string          `json:"id"`
	AccountID   string          `json:"accountId"`
	Amount      string          `json:"amount"`
	Type        TransactionType `json:"type"`
	Category    *string         `json:"category,omitempty"`
	Description *string         `json:"description,omitempty"`
	Date        time.Time       `json:"date"`
	CreatedAt   time.Time       `json:"createdAt"`
}

type User struct {
	ID        string     `json:"id"`
	Email     string     `json:"email"`
	Name      string     `json:"name"`
	Accounts  []*Account `json:"accounts"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type AccountType string

const (
	AccountTypeChecking   AccountType = "CHECKING"
	AccountTypeSavings    AccountType = "SAVINGS"
	AccountTypeCredit     AccountType = "CREDIT"
	AccountTypeInvestment AccountType = "INVESTMENT"
)

var AllAccountType = []AccountType{
	AccountTypeChecking,
	AccountTypeSavings,
	AccountTypeCredit,
	AccountTypeInvestment,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeChecking, AccountTypeSavings, AccountTypeCredit, AccountTypeInvestment:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionType string

const (
	TransactionTypeIncome   TransactionType = "INCOME"
	TransactionTypeExpense  TransactionType = "EXPENSE"
	TransactionTypeTransfer TransactionType = "TRANSFER"
)

var AllTransactionType = []TransactionType{
	TransactionTypeIncome,
	TransactionTypeExpense,
	TransactionTypeTransfer,
}

func (e TransactionType) IsValid() bool {
	switch e {
	case TransactionTypeIncome, TransactionTypeExpense, TransactionTypeTransfer:
		return true
	}
	return false
}

func (e TransactionType) String() string {
	return string(e)
}

func (e *TransactionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionType", str)
	}
	return nil
}

func (e TransactionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
